"""add surname

Revision ID: 6d48a57f84c2
Revises: a3d746c6b636
Create Date: 2024-10-03 12:58:56.765237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d48a57f84c2'
down_revision = 'a3d746c6b636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('surname', sa.String(length=32), nullable=True))
        batch_op.create_index(batch_op.f('ix_authors_surname'), ['surname'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authors_surname'))
        batch_op.drop_column('surname')

    # ### end Alembic commands ###
